### ISSUE TITLE
Unnexistant item

### ISSUE THREAD

**Issue by thibeck** [cauliflower69/Requiem-HQM#11]
Hey man, in the Thermal Expansion quest tree there's a quest called "Show me the way!", in this quest you need to craft an "Empty Armor Plating", but there's no item called "Empty Armor Plating" in NEI.
If you could help me I'll be very happy.
Thanks

**Comment by cauliflower69** [comment]
Go into creative mode and use the command /hqm edit (yourIGN) shift right click the quest and it will auto complete. 

Thanks for the feedback

**Comment by thibeck** [comment]
Thanks man!
