### ISSUE TITLE
HQM - ProjectE Questline

### ISSUE THREAD

**Issue by XxShadowX** [cauliflower69/Requiem-HQM#3]
None of the quests have a reward, Not even a lousy bag that trolls you with firestone ore! :P

**Comment by aaronhowser1** [comment]
I'll see about adding rewards. A lot of quests don't have them, and I really don't have any idea what to put for most of them

**Comment by cauliflower69** [comment]
XxShadowX any ideas of rewards ?

**Comment by XxShadowX** [comment]
In all honesty id say just do reward bags. Maybe some of the early quests give you a bit of a boost in emc or something? Couple dark/redmatter here and there?

Wil have a proper look at the quests later then let you know

**Comment by cauliflower69** [comment]
Thanks dude

**Comment by cauliflower69** [comment]
Should be fixed in V11
