### ISSUE TITLE
Config change

### ISSUE THREAD

**Issue by XxShadowX** [cauliflower69/Requiem-HQM#4]
Mekanism.cfg - Prefilled portable tanks = true - Change to false to remove all liquids being rendered in nei.

Openblocks.cfg - displayAllFluids=true - Change to false for same reason above.

**Comment by cauliflower69** [comment]
Thanks - will be done in the next update

**Comment by XxShadowX** [comment]
Also the cofh core config that announces all named mob deaths too.

**Comment by cauliflower69** [comment]
lol I was just changing the cfg as I got the email message, thanks again
