### ISSUE TITLE
Resetting quests/achievements 

### ISSUE THREAD

**Issue by quincylennard** [cauliflower69/Requiem-HQM#6]
This probably isn't specific to this modpack: anytime I close my game window, my achievements and HQM quests are reset, meaning opening my inventory unlocks "Getting Inventory" again and all quests sets are back at zero completion. Any idea what might be causing this?

**Comment by cauliflower69** [comment]
Sorry I may not be of great help but it sounds like you may have some permission issues with writing to the directory
