### ISSUE TITLE
Chapter 2 - Novice Tinkerer Issue

### ISSUE THREAD

**Issue by Nargath** [cauliflower69/Requiem-HQM#8]
I've tried to build a part builder in Chapter 2, and the Novice Tinkerer step, but its not registering the Part Builder.

I've tried giving myself every iteration of Part Builder, but none are registering in the quest.

**Comment by XxShadowX** [comment]
If by giving yourself every iteration of it you mean spawning it in, that wont work. Iirc its a crafting task.

**Comment by Nargath** [comment]
I spawned them in after I tried crafting one using all the raw wood I could find.

And of course, I tried it again, and it worked. So problem solved!

**Comment by XxShadowX** [comment]
Normally just crafting it then checking the book with said item in your
inventory works

**Comment by Nargath** [comment]
Yeah, I had done that, but didn't register.
I think restarting MC must of clicked it in
