### ISSUE TITLE
Been searching for an instuctional modpack, thanks!  but.. this one won't finish loading, running it from Technics launcher, it hangs up at 1/7 in the minecraft loading screen

### ISSUE THREAD

**Issue by Unatan63** [cauliflower69/Requiem-HQM#9]

**Comment by cauliflower69** [comment]
My first guess would be ram allocation. Increase to 3-4 gb

**Comment by Winja** [comment]
I have the same problem, also with V2 but the increase of RAM didnt work!

**Comment by Winja** [comment]
Solved it! Upgrading my Java to version 8 did the trick for both packs

**Comment by cauliflower69** [comment]
Glad you got it sorted
